### ISSUE TITLE
Java Class Not Found PSPDFKITPlugin.java When File Is Present

### ISSUE THREAD

**Issue by adamcweitzman** [PSPDFKit/PSPDFKit-Cordova#16]
Using pspdfkit as a cordova plugin in an ionic project, generating an apk and running the app as a beta in the play store, when opening a pdf the system error is:

01-06 15:45:49.076  8120  8250 W System.err: java.lang.ClassNotFoundException: com.pspdfkit.cordova.PSPDFKitPlugin
01-06 15:45:49.076  8120  8250 W System.err:    at java.lang.Class.classForName(Native Method)
01-06 15:45:49.076  8120  8250 W System.err:    at java.lang.Class.forName(Class.java:453)
01-06 15:45:49.076  8120  8250 W System.err:    at java.lang.Class.forName(Class.java:378)
01-06 15:45:49.076  8120  8250 W System.err:    at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
01-06 15:45:49.076  8120  8250 W System.err:    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
01-06 15:45:49.076  8120  8250 W System.err:    at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
01-06 15:45:49.076  8120  8250 W System.err:    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
01-06 15:45:49.076  8120  8250 W System.err:    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
01-06 15:45:49.076  8120  8250 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
01-06 15:45:49.076  8120  8250 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:326)
01-06 15:45:49.076  8120  8250 W System.err:    at android.os.Looper.loop(Looper.java:181)
01-06 15:45:49.076  8120  8250 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:65)# Details

The file is present in the file system, and the plugin.xml looks good to me, so not sure whats going on here...

**Comment by skoric** [comment]
@adamcweitzman Hi, have you managed to resolve this issue in the meanwhile?
